// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

/** Represents the preset quality of the audio and video stream. */
export enum Quality {
  /** QUALITY_UNSPECIFIED - The default value. */
  QUALITY_UNSPECIFIED = 0,
  /** QUALITY_LOW - The lowest quality, with the lowest bitrate and resolution. */
  QUALITY_LOW = 1,
  /** QUALITY_MEDIUM - The medium quality, with a moderate bitrate and resolution. */
  QUALITY_MEDIUM = 2,
  /** QUALITY_HIGH - The highest quality, with the highest bitrate and resolution. */
  QUALITY_HIGH = 3,
  UNRECOGNIZED = -1,
}

export function qualityFromJSON(object: any): Quality {
  switch (object) {
    case 0:
    case "QUALITY_UNSPECIFIED":
      return Quality.QUALITY_UNSPECIFIED;
    case 1:
    case "QUALITY_LOW":
      return Quality.QUALITY_LOW;
    case 2:
    case "QUALITY_MEDIUM":
      return Quality.QUALITY_MEDIUM;
    case 3:
    case "QUALITY_HIGH":
      return Quality.QUALITY_HIGH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Quality.UNRECOGNIZED;
  }
}

export function qualityToJSON(object: Quality): string {
  switch (object) {
    case Quality.QUALITY_UNSPECIFIED:
      return "QUALITY_UNSPECIFIED";
    case Quality.QUALITY_LOW:
      return "QUALITY_LOW";
    case Quality.QUALITY_MEDIUM:
      return "QUALITY_MEDIUM";
    case Quality.QUALITY_HIGH:
      return "QUALITY_HIGH";
    case Quality.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Represents the type of session connected to the server. */
export enum SessionType {
  /** SESSION_TYPE_UNKNOWN - The default value. */
  SESSION_TYPE_UNKNOWN = 0,
  /** SESSION_TYPE_CONTROLLER - A session for a controller. */
  SESSION_TYPE_CONTROLLER = 1,
  /** SESSION_TYPE_STREAMER - A session for a streamer. */
  SESSION_TYPE_STREAMER = 2,
  /** SESSION_TYPE_VIEWER - A session for a viewer. */
  SESSION_TYPE_VIEWER = 3,
  UNRECOGNIZED = -1,
}

export function sessionTypeFromJSON(object: any): SessionType {
  switch (object) {
    case 0:
    case "SESSION_TYPE_UNKNOWN":
      return SessionType.SESSION_TYPE_UNKNOWN;
    case 1:
    case "SESSION_TYPE_CONTROLLER":
      return SessionType.SESSION_TYPE_CONTROLLER;
    case 2:
    case "SESSION_TYPE_STREAMER":
      return SessionType.SESSION_TYPE_STREAMER;
    case 3:
    case "SESSION_TYPE_VIEWER":
      return SessionType.SESSION_TYPE_VIEWER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SessionType.UNRECOGNIZED;
  }
}

export function sessionTypeToJSON(object: SessionType): string {
  switch (object) {
    case SessionType.SESSION_TYPE_UNKNOWN:
      return "SESSION_TYPE_UNKNOWN";
    case SessionType.SESSION_TYPE_CONTROLLER:
      return "SESSION_TYPE_CONTROLLER";
    case SessionType.SESSION_TYPE_STREAMER:
      return "SESSION_TYPE_STREAMER";
    case SessionType.SESSION_TYPE_VIEWER:
      return "SESSION_TYPE_VIEWER";
    case SessionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Requests to answer an WebRTC offer from the streamer to establish a WebRTC connection. */
export interface RequestRtcAnswer {
  /** The ID of the streamer to request the WebRTC answer from. */
  streamerId: number;
  /** The offer created by the streamer in response to the viewer or controller's request. */
  offer: string;
  /** The video transform from the streamer to apply to the stream. */
  videoTransform?: VideoTransform | undefined;
}

/** Response to the viewer or controller's request for an WebRTC offer, containing the answer of the WebRTC offer. */
export interface RtcAnswerResponse {
  /** The ID of the streamer that created the offer. */
  streamerId: number;
  /** The answer created by the streamer in response to the viewer or controller's request. */
  answer: string;
}

/** Represents an ICE candidate from the streamer or viewer. */
export interface IceCandidate {
  /** The ID of the session that the candidate is for or from. */
  session:
    | Session
    | undefined;
  /** The candidate string. */
  candidate: string;
}

/** Represents the video transform (CSS-based zoom level) applied to the stream. */
export interface VideoTransform {
  /** The zoom level to apply to the stream. A value of 1.0 means no zoom, while a value greater than 1.0 means zoom in and a value less than 1.0 means zoom out. */
  zoom: number;
  /** The rotation to apply to the stream in degrees. A value of 0 means no rotation, while a value of 90 means rotate 90 degrees clockwise, and a value of -90 means rotate 90 degrees counterclockwise. */
  rotation: number;
}

/** / Represents a update request for the video transform (CSS-based zoom level) applied to the stream. */
export interface UpdateVideoTransform {
  /** The ID of the streamer to update the video transform for. */
  streamerId: number;
  /** The new video transform to apply to the stream. */
  videoTransform: VideoTransform | undefined;
}

/** Represents a session ID and type, which can be used to identify a session in the server. */
export interface Session {
  /** The ID of the session. */
  id: number;
  /** The type of the session. */
  type: SessionType;
}

function createBaseRequestRtcAnswer(): RequestRtcAnswer {
  return { streamerId: 0, offer: "", videoTransform: undefined };
}

export const RequestRtcAnswer: MessageFns<RequestRtcAnswer> = {
  encode(message: RequestRtcAnswer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.offer !== "") {
      writer.uint32(18).string(message.offer);
    }
    if (message.videoTransform !== undefined) {
      VideoTransform.encode(message.videoTransform, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestRtcAnswer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestRtcAnswer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.offer = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.videoTransform = VideoTransform.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestRtcAnswer {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      offer: isSet(object.offer) ? globalThis.String(object.offer) : "",
      videoTransform: isSet(object.videoTransform)
        ? VideoTransform.fromJSON(object.videoTransform)
        : isSet(object.video_transform)
        ? VideoTransform.fromJSON(object.video_transform)
        : undefined,
    };
  },

  toJSON(message: RequestRtcAnswer): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.offer !== "") {
      obj.offer = message.offer;
    }
    if (message.videoTransform !== undefined) {
      obj.videoTransform = VideoTransform.toJSON(message.videoTransform);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestRtcAnswer>, I>>(base?: I): RequestRtcAnswer {
    return RequestRtcAnswer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestRtcAnswer>, I>>(object: I): RequestRtcAnswer {
    const message = createBaseRequestRtcAnswer();
    message.streamerId = object.streamerId ?? 0;
    message.offer = object.offer ?? "";
    message.videoTransform = (object.videoTransform !== undefined && object.videoTransform !== null)
      ? VideoTransform.fromPartial(object.videoTransform)
      : undefined;
    return message;
  },
};

function createBaseRtcAnswerResponse(): RtcAnswerResponse {
  return { streamerId: 0, answer: "" };
}

export const RtcAnswerResponse: MessageFns<RtcAnswerResponse> = {
  encode(message: RtcAnswerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.answer !== "") {
      writer.uint32(18).string(message.answer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcAnswerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcAnswerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RtcAnswerResponse {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
    };
  },

  toJSON(message: RtcAnswerResponse): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RtcAnswerResponse>, I>>(base?: I): RtcAnswerResponse {
    return RtcAnswerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcAnswerResponse>, I>>(object: I): RtcAnswerResponse {
    const message = createBaseRtcAnswerResponse();
    message.streamerId = object.streamerId ?? 0;
    message.answer = object.answer ?? "";
    return message;
  },
};

function createBaseIceCandidate(): IceCandidate {
  return { session: undefined, candidate: "" };
}

export const IceCandidate: MessageFns<IceCandidate> = {
  encode(message: IceCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.candidate !== "") {
      writer.uint32(18).string(message.candidate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IceCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIceCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IceCandidate {
    return {
      session: isSet(object.session) ? Session.fromJSON(object.session) : undefined,
      candidate: isSet(object.candidate) ? globalThis.String(object.candidate) : "",
    };
  },

  toJSON(message: IceCandidate): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.candidate !== "") {
      obj.candidate = message.candidate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IceCandidate>, I>>(base?: I): IceCandidate {
    return IceCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IceCandidate>, I>>(object: I): IceCandidate {
    const message = createBaseIceCandidate();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    message.candidate = object.candidate ?? "";
    return message;
  },
};

function createBaseVideoTransform(): VideoTransform {
  return { zoom: 0, rotation: 0 };
}

export const VideoTransform: MessageFns<VideoTransform> = {
  encode(message: VideoTransform, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.zoom !== 0) {
      writer.uint32(13).float(message.zoom);
    }
    if (message.rotation !== 0) {
      writer.uint32(16).int32(message.rotation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VideoTransform {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVideoTransform();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.zoom = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rotation = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VideoTransform {
    return {
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0,
      rotation: isSet(object.rotation) ? globalThis.Number(object.rotation) : 0,
    };
  },

  toJSON(message: VideoTransform): unknown {
    const obj: any = {};
    if (message.zoom !== 0) {
      obj.zoom = message.zoom;
    }
    if (message.rotation !== 0) {
      obj.rotation = Math.round(message.rotation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VideoTransform>, I>>(base?: I): VideoTransform {
    return VideoTransform.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VideoTransform>, I>>(object: I): VideoTransform {
    const message = createBaseVideoTransform();
    message.zoom = object.zoom ?? 0;
    message.rotation = object.rotation ?? 0;
    return message;
  },
};

function createBaseUpdateVideoTransform(): UpdateVideoTransform {
  return { streamerId: 0, videoTransform: undefined };
}

export const UpdateVideoTransform: MessageFns<UpdateVideoTransform> = {
  encode(message: UpdateVideoTransform, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.videoTransform !== undefined) {
      VideoTransform.encode(message.videoTransform, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateVideoTransform {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateVideoTransform();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.videoTransform = VideoTransform.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateVideoTransform {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      videoTransform: isSet(object.videoTransform)
        ? VideoTransform.fromJSON(object.videoTransform)
        : isSet(object.video_transform)
        ? VideoTransform.fromJSON(object.video_transform)
        : undefined,
    };
  },

  toJSON(message: UpdateVideoTransform): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.videoTransform !== undefined) {
      obj.videoTransform = VideoTransform.toJSON(message.videoTransform);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateVideoTransform>, I>>(base?: I): UpdateVideoTransform {
    return UpdateVideoTransform.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateVideoTransform>, I>>(object: I): UpdateVideoTransform {
    const message = createBaseUpdateVideoTransform();
    message.streamerId = object.streamerId ?? 0;
    message.videoTransform = (object.videoTransform !== undefined && object.videoTransform !== null)
      ? VideoTransform.fromPartial(object.videoTransform)
      : undefined;
    return message;
  },
};

function createBaseSession(): Session {
  return { id: 0, type: 0 };
}

export const Session: MessageFns<Session> = {
  encode(message: Session, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      type: isSet(object.type) ? sessionTypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.type !== 0) {
      obj.type = sessionTypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.id = object.id ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
