// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: controller.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  IceCandidate,
  Quality,
  qualityFromJSON,
  qualityToJSON,
  RequestRtcAnswer,
  RtcAnswerResponse,
  Session,
  UpdateVideoTransform,
} from "./common";

export const protobufPackage = "controller";

/** The controller is ready to receive commands from the server. */
export interface Ready {
  /** The ID of the controller that is ready. */
  id: number;
  /** The list of streamers connected to the server. */
  streamers: StreamerSession[];
  /** The number of viewers connected to the server. */
  viewerCount: number;
}

/** Contains the different commands that the controller can send to the server. */
export interface ClientToServer {
  /** Responds to the streamer WebRTC offer. */
  rtcAnswerResponse?:
    | RtcAnswerResponse
    | undefined;
  /** Controller is requesting a change in the quality of the stream from the streamer. */
  requestChangeQuality?:
    | RequestChangeQuality
    | undefined;
  /** Controller is requesting the list of streamers connected to the server. */
  listStreamers?:
    | ListStreamers
    | undefined;
  /** Controller is requesting the list of viewers connected to a specific streamer or not watching any streamer. */
  listViewers?:
    | ListViewers
    | undefined;
  /** Controller is requesting the list of all viewers connected to the server. */
  listAllViewers?:
    | ListAllViewers
    | undefined;
  /** Controller is sending an ICE candidate to the streamer to establish a WebRTC connection. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** Controller is requesting the streamer to update the zoom level applied to the stream. */
  requestZoom?:
    | RequestZoom
    | undefined;
  /** / Controller is requesting a viewer to update which streamer they are watching. */
  updateWatching?:
    | UpdateWatching
    | undefined;
  /** Controller is requesting the streamer to update the mute status of the stream. */
  requestMute?:
    | RequestChangeMute
    | undefined;
  /** Ask streamer for a WebRTC offer */
  requestRtcOffer?: RequestRtcOffer | undefined;
}

/** Contains the different commands that the server can send to the controller. */
export interface ServerToClient {
  /** The streamer is requesting the controller to answer the RTC offer created by the streamer to establish a WebRTC connection. */
  requestRtcAnswer?:
    | RequestRtcAnswer
    | undefined;
  /** The streamer has requested to update the CSS-based zoom level applied to the stream. */
  updateVideoTransform?:
    | UpdateVideoTransform
    | undefined;
  /** Sent by the streamer to the controller when the streamer updates its battery level. */
  batteryLevel?:
    | BatteryLevel
    | undefined;
  /** The streamer will send an ICE candidate to the controller to establish a WebRTC connection. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** The streamer has updated the universal zoom level applied to the stream. */
  updateZoom?:
    | UpdateZoom
    | undefined;
  /** The server will send the list of streamers connected to the server. */
  listStreamersResponse?:
    | ListStreamersResponse
    | undefined;
  /** The server will send the list of viewers connected to the server in response to the controller's request. */
  listViewersResponse?:
    | ListViewersResponse
    | undefined;
  /** The server will send a notification to the controller when a new session, either a streamer or viewer, has connected to the server, when a session has disconnected from the server, or when a viewer has changed which streamer they are watching. */
  newSession?:
    | NewSession
    | undefined;
  /** The server will send a notification to the controller when a session, either a streamer or viewer, has disconnected from the server. */
  dropSession?:
    | DropSession
    | undefined;
  /** The server will send a notification to the controller when a viewer has changed which streamer they are watching. */
  changedWatching?:
    | ChangedWatching
    | undefined;
  /** The viewer has changed the mute status of their own. */
  changedMute?:
    | ChangedMute
    | undefined;
  /** The streamer has changed the quality of their stream. */
  changedQuality?: ChangedQuality | undefined;
}

/** Requests a change in the quality of the stream from the streamer. */
export interface RequestChangeQuality {
  /** The ID of the streamer to change the quality for. */
  streamerId: number;
  /** The new quality to set for the stream. */
  quality: Quality;
}

/** Requests the list of streamers connected to the server. */
export interface ListStreamers {
}

/** Requests the list of viewers connected to the server based on if they are watching a specific streamer or not. */
export interface ListViewers {
  /** The ID of the streamer to list the viewers for. If not provided, the server will return the list of viewers that are not watching any streamer. */
  streamerId?: number | undefined;
}

/** Requests the list of all viewers connected to the server. */
export interface ListAllViewers {
}

/** Response to a request for the list of streamers connected to the server. */
export interface ListStreamersResponse {
  /** The list of streamers connected to the server. */
  streamers: StreamerSession[];
}

/** Response to a request for the list of viewers connected to the server. */
export interface ListViewersResponse {
  /** The list of viewers connected to the server. */
  viewers: ViewerSession[];
}

/** Represents a new session that has connected to the server, either a streamer or a viewer. */
export interface NewSession {
  /** A new streamer has connected to the server. */
  streamerSession?:
    | StreamerSession
    | undefined;
  /** A new viewer has connected to the server. */
  viewerSession?: ViewerSession | undefined;
}

/** Represents a session that has disconnected from the server, either a streamer or a viewer. */
export interface DropSession {
  /** The session that has disconnected from the server, either a streamer or a viewer. */
  session: Session | undefined;
}

/** Represents a viewer that has changed which streamer they are watching. */
export interface ChangedWatching {
  /** The ID of the viewer that has changed which streamer they are watching. */
  viewerId: number;
  /** The ID of the streamer that the viewer is now watching. If not provided, the viewer is not watching any streamer. */
  streamerId?: number | undefined;
}

/** Represents a streamer session connected to the server. */
export interface StreamerSession {
  /** The ID of the streamer. */
  id: number;
  /** The name of the streamer. */
  name?:
    | string
    | undefined;
  /** The zoom level of the streamer. */
  zoom?:
    | number
    | undefined;
  /** The battery level of the streamer, represented as a percentage from 0 to 100. */
  batteryLevel?: number | undefined;
}

/** Represents a viewer session connected to the server. */
export interface ViewerSession {
  /** The ID of the viewer. */
  id: number;
  /** The name of the viewer. */
  name?:
    | string
    | undefined;
  /** The ID of the streamer the viewer is connected to. */
  streamerId?: number | undefined;
}

/** The streamer is updating its battery level. */
export interface BatteryLevel {
  /** The ID of the streamer that has updated its battery level. */
  streamerId: number;
  /** The new battery level, represented as a percentage from 0 to 100. */
  batteryLevel: number;
}

/** Requests the streamer to update the universal zoom level applied to the stream. */
export interface RequestZoom {
  /** The ID of the streamer to request the zoom level for. */
  streamerId: number;
  /** The new zoom level to set for the stream. */
  zoom: number;
}

/** Represents a streamer that has updated its universal zoom level. */
export interface UpdateZoom {
  /** The ID of the streamer that has updated its zoom level. */
  streamerId: number;
  /** The new zoom level that the streamer has updated to. */
  zoom: number;
}

/** Update sent by the controller to the server when a viewer should update which streamer they are watching. */
export interface UpdateWatching {
  /** The ID of the viewer that has updated which streamer they are watching. */
  viewerId: number;
  /** The ID of the streamer that the viewer is now watching. If not provided, the viewer is not watching any streamer. */
  streamerId?: number | undefined;
}

/** Requests the viewer to update the mute status of the stream. */
export interface RequestChangeMute {
  /** The ID of the viewer to request the mute status change for. */
  viewerId: number;
  /** The new mute status to set for the stream. A value of true means to mute the stream, while a value of false means to un-mute the stream. */
  muted: boolean;
}

/** Streamer has changed the quality of their stream. */
export interface ChangedQuality {
  /** The ID of the streamer that has changed the quality of their stream. */
  streamerId: number;
  /** The new quality that the streamer has changed to. */
  quality: Quality;
}

/** The viewer has changed the mute status of their own stream. */
export interface ChangedMute {
  /** The ID of the viewer that has changed the mute status of their stream. */
  viewerId: number;
  /** The new mute status that the viewer has changed to. A value of true means the stream is now muted, while a value of false means the stream is now un-muted. */
  muted: boolean;
}

/** The controller is asking a streamer for an offer for the builtin preview. */
export interface RequestRtcOffer {
  /** The ID of the streamer that should create an offer. */
  streamerId: number;
}

function createBaseReady(): Ready {
  return { id: 0, streamers: [], viewerCount: 0 };
}

export const Ready: MessageFns<Ready> = {
  encode(message: Ready, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    for (const v of message.streamers) {
      StreamerSession.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.viewerCount !== 0) {
      writer.uint32(24).uint32(message.viewerCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ready {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReady();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.streamers.push(StreamerSession.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.viewerCount = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ready {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      streamers: globalThis.Array.isArray(object?.streamers)
        ? object.streamers.map((e: any) => StreamerSession.fromJSON(e))
        : [],
      viewerCount: isSet(object.viewerCount)
        ? globalThis.Number(object.viewerCount)
        : isSet(object.viewer_count)
        ? globalThis.Number(object.viewer_count)
        : 0,
    };
  },

  toJSON(message: Ready): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.streamers?.length) {
      obj.streamers = message.streamers.map((e) => StreamerSession.toJSON(e));
    }
    if (message.viewerCount !== 0) {
      obj.viewerCount = Math.round(message.viewerCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ready>, I>>(base?: I): Ready {
    return Ready.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ready>, I>>(object: I): Ready {
    const message = createBaseReady();
    message.id = object.id ?? 0;
    message.streamers = object.streamers?.map((e) => StreamerSession.fromPartial(e)) || [];
    message.viewerCount = object.viewerCount ?? 0;
    return message;
  },
};

function createBaseClientToServer(): ClientToServer {
  return {
    rtcAnswerResponse: undefined,
    requestChangeQuality: undefined,
    listStreamers: undefined,
    listViewers: undefined,
    listAllViewers: undefined,
    iceCandidate: undefined,
    requestZoom: undefined,
    updateWatching: undefined,
    requestMute: undefined,
    requestRtcOffer: undefined,
  };
}

export const ClientToServer: MessageFns<ClientToServer> = {
  encode(message: ClientToServer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rtcAnswerResponse !== undefined) {
      RtcAnswerResponse.encode(message.rtcAnswerResponse, writer.uint32(10).fork()).join();
    }
    if (message.requestChangeQuality !== undefined) {
      RequestChangeQuality.encode(message.requestChangeQuality, writer.uint32(18).fork()).join();
    }
    if (message.listStreamers !== undefined) {
      ListStreamers.encode(message.listStreamers, writer.uint32(26).fork()).join();
    }
    if (message.listViewers !== undefined) {
      ListViewers.encode(message.listViewers, writer.uint32(34).fork()).join();
    }
    if (message.listAllViewers !== undefined) {
      ListAllViewers.encode(message.listAllViewers, writer.uint32(42).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(50).fork()).join();
    }
    if (message.requestZoom !== undefined) {
      RequestZoom.encode(message.requestZoom, writer.uint32(58).fork()).join();
    }
    if (message.updateWatching !== undefined) {
      UpdateWatching.encode(message.updateWatching, writer.uint32(66).fork()).join();
    }
    if (message.requestMute !== undefined) {
      RequestChangeMute.encode(message.requestMute, writer.uint32(74).fork()).join();
    }
    if (message.requestRtcOffer !== undefined) {
      RequestRtcOffer.encode(message.requestRtcOffer, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientToServer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientToServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rtcAnswerResponse = RtcAnswerResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requestChangeQuality = RequestChangeQuality.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.listStreamers = ListStreamers.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.listViewers = ListViewers.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.listAllViewers = ListAllViewers.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestZoom = RequestZoom.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updateWatching = UpdateWatching.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.requestMute = RequestChangeMute.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.requestRtcOffer = RequestRtcOffer.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientToServer {
    return {
      rtcAnswerResponse: isSet(object.rtcAnswerResponse)
        ? RtcAnswerResponse.fromJSON(object.rtcAnswerResponse)
        : isSet(object.rtc_answer_response)
        ? RtcAnswerResponse.fromJSON(object.rtc_answer_response)
        : undefined,
      requestChangeQuality: isSet(object.requestChangeQuality)
        ? RequestChangeQuality.fromJSON(object.requestChangeQuality)
        : isSet(object.request_change_quality)
        ? RequestChangeQuality.fromJSON(object.request_change_quality)
        : undefined,
      listStreamers: isSet(object.listStreamers)
        ? ListStreamers.fromJSON(object.listStreamers)
        : isSet(object.list_streamers)
        ? ListStreamers.fromJSON(object.list_streamers)
        : undefined,
      listViewers: isSet(object.listViewers)
        ? ListViewers.fromJSON(object.listViewers)
        : isSet(object.list_viewers)
        ? ListViewers.fromJSON(object.list_viewers)
        : undefined,
      listAllViewers: isSet(object.listAllViewers)
        ? ListAllViewers.fromJSON(object.listAllViewers)
        : isSet(object.list_all_viewers)
        ? ListAllViewers.fromJSON(object.list_all_viewers)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      requestZoom: isSet(object.requestZoom)
        ? RequestZoom.fromJSON(object.requestZoom)
        : isSet(object.request_zoom)
        ? RequestZoom.fromJSON(object.request_zoom)
        : undefined,
      updateWatching: isSet(object.updateWatching)
        ? UpdateWatching.fromJSON(object.updateWatching)
        : isSet(object.update_watching)
        ? UpdateWatching.fromJSON(object.update_watching)
        : undefined,
      requestMute: isSet(object.requestMute)
        ? RequestChangeMute.fromJSON(object.requestMute)
        : isSet(object.request_mute)
        ? RequestChangeMute.fromJSON(object.request_mute)
        : undefined,
      requestRtcOffer: isSet(object.requestRtcOffer)
        ? RequestRtcOffer.fromJSON(object.requestRtcOffer)
        : isSet(object.request_rtc_offer)
        ? RequestRtcOffer.fromJSON(object.request_rtc_offer)
        : undefined,
    };
  },

  toJSON(message: ClientToServer): unknown {
    const obj: any = {};
    if (message.rtcAnswerResponse !== undefined) {
      obj.rtcAnswerResponse = RtcAnswerResponse.toJSON(message.rtcAnswerResponse);
    }
    if (message.requestChangeQuality !== undefined) {
      obj.requestChangeQuality = RequestChangeQuality.toJSON(message.requestChangeQuality);
    }
    if (message.listStreamers !== undefined) {
      obj.listStreamers = ListStreamers.toJSON(message.listStreamers);
    }
    if (message.listViewers !== undefined) {
      obj.listViewers = ListViewers.toJSON(message.listViewers);
    }
    if (message.listAllViewers !== undefined) {
      obj.listAllViewers = ListAllViewers.toJSON(message.listAllViewers);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.requestZoom !== undefined) {
      obj.requestZoom = RequestZoom.toJSON(message.requestZoom);
    }
    if (message.updateWatching !== undefined) {
      obj.updateWatching = UpdateWatching.toJSON(message.updateWatching);
    }
    if (message.requestMute !== undefined) {
      obj.requestMute = RequestChangeMute.toJSON(message.requestMute);
    }
    if (message.requestRtcOffer !== undefined) {
      obj.requestRtcOffer = RequestRtcOffer.toJSON(message.requestRtcOffer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientToServer>, I>>(base?: I): ClientToServer {
    return ClientToServer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientToServer>, I>>(object: I): ClientToServer {
    const message = createBaseClientToServer();
    message.rtcAnswerResponse = (object.rtcAnswerResponse !== undefined && object.rtcAnswerResponse !== null)
      ? RtcAnswerResponse.fromPartial(object.rtcAnswerResponse)
      : undefined;
    message.requestChangeQuality = (object.requestChangeQuality !== undefined && object.requestChangeQuality !== null)
      ? RequestChangeQuality.fromPartial(object.requestChangeQuality)
      : undefined;
    message.listStreamers = (object.listStreamers !== undefined && object.listStreamers !== null)
      ? ListStreamers.fromPartial(object.listStreamers)
      : undefined;
    message.listViewers = (object.listViewers !== undefined && object.listViewers !== null)
      ? ListViewers.fromPartial(object.listViewers)
      : undefined;
    message.listAllViewers = (object.listAllViewers !== undefined && object.listAllViewers !== null)
      ? ListAllViewers.fromPartial(object.listAllViewers)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.requestZoom = (object.requestZoom !== undefined && object.requestZoom !== null)
      ? RequestZoom.fromPartial(object.requestZoom)
      : undefined;
    message.updateWatching = (object.updateWatching !== undefined && object.updateWatching !== null)
      ? UpdateWatching.fromPartial(object.updateWatching)
      : undefined;
    message.requestMute = (object.requestMute !== undefined && object.requestMute !== null)
      ? RequestChangeMute.fromPartial(object.requestMute)
      : undefined;
    message.requestRtcOffer = (object.requestRtcOffer !== undefined && object.requestRtcOffer !== null)
      ? RequestRtcOffer.fromPartial(object.requestRtcOffer)
      : undefined;
    return message;
  },
};

function createBaseServerToClient(): ServerToClient {
  return {
    requestRtcAnswer: undefined,
    updateVideoTransform: undefined,
    batteryLevel: undefined,
    iceCandidate: undefined,
    updateZoom: undefined,
    listStreamersResponse: undefined,
    listViewersResponse: undefined,
    newSession: undefined,
    dropSession: undefined,
    changedWatching: undefined,
    changedMute: undefined,
    changedQuality: undefined,
  };
}

export const ServerToClient: MessageFns<ServerToClient> = {
  encode(message: ServerToClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestRtcAnswer !== undefined) {
      RequestRtcAnswer.encode(message.requestRtcAnswer, writer.uint32(10).fork()).join();
    }
    if (message.updateVideoTransform !== undefined) {
      UpdateVideoTransform.encode(message.updateVideoTransform, writer.uint32(18).fork()).join();
    }
    if (message.batteryLevel !== undefined) {
      BatteryLevel.encode(message.batteryLevel, writer.uint32(26).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(34).fork()).join();
    }
    if (message.updateZoom !== undefined) {
      UpdateZoom.encode(message.updateZoom, writer.uint32(42).fork()).join();
    }
    if (message.listStreamersResponse !== undefined) {
      ListStreamersResponse.encode(message.listStreamersResponse, writer.uint32(50).fork()).join();
    }
    if (message.listViewersResponse !== undefined) {
      ListViewersResponse.encode(message.listViewersResponse, writer.uint32(58).fork()).join();
    }
    if (message.newSession !== undefined) {
      NewSession.encode(message.newSession, writer.uint32(66).fork()).join();
    }
    if (message.dropSession !== undefined) {
      DropSession.encode(message.dropSession, writer.uint32(74).fork()).join();
    }
    if (message.changedWatching !== undefined) {
      ChangedWatching.encode(message.changedWatching, writer.uint32(82).fork()).join();
    }
    if (message.changedMute !== undefined) {
      ChangedMute.encode(message.changedMute, writer.uint32(90).fork()).join();
    }
    if (message.changedQuality !== undefined) {
      ChangedQuality.encode(message.changedQuality, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerToClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerToClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestRtcAnswer = RequestRtcAnswer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateVideoTransform = UpdateVideoTransform.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.batteryLevel = BatteryLevel.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updateZoom = UpdateZoom.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.listStreamersResponse = ListStreamersResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.listViewersResponse = ListViewersResponse.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.newSession = NewSession.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.dropSession = DropSession.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.changedWatching = ChangedWatching.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.changedMute = ChangedMute.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.changedQuality = ChangedQuality.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerToClient {
    return {
      requestRtcAnswer: isSet(object.requestRtcAnswer)
        ? RequestRtcAnswer.fromJSON(object.requestRtcAnswer)
        : isSet(object.request_rtc_answer)
        ? RequestRtcAnswer.fromJSON(object.request_rtc_answer)
        : undefined,
      updateVideoTransform: isSet(object.updateVideoTransform)
        ? UpdateVideoTransform.fromJSON(object.updateVideoTransform)
        : isSet(object.update_video_transform)
        ? UpdateVideoTransform.fromJSON(object.update_video_transform)
        : undefined,
      batteryLevel: isSet(object.batteryLevel)
        ? BatteryLevel.fromJSON(object.batteryLevel)
        : isSet(object.battery_level)
        ? BatteryLevel.fromJSON(object.battery_level)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      updateZoom: isSet(object.updateZoom)
        ? UpdateZoom.fromJSON(object.updateZoom)
        : isSet(object.update_zoom)
        ? UpdateZoom.fromJSON(object.update_zoom)
        : undefined,
      listStreamersResponse: isSet(object.listStreamersResponse)
        ? ListStreamersResponse.fromJSON(object.listStreamersResponse)
        : isSet(object.list_streamers_response)
        ? ListStreamersResponse.fromJSON(object.list_streamers_response)
        : undefined,
      listViewersResponse: isSet(object.listViewersResponse)
        ? ListViewersResponse.fromJSON(object.listViewersResponse)
        : isSet(object.list_viewers_response)
        ? ListViewersResponse.fromJSON(object.list_viewers_response)
        : undefined,
      newSession: isSet(object.newSession)
        ? NewSession.fromJSON(object.newSession)
        : isSet(object.new_session)
        ? NewSession.fromJSON(object.new_session)
        : undefined,
      dropSession: isSet(object.dropSession)
        ? DropSession.fromJSON(object.dropSession)
        : isSet(object.drop_session)
        ? DropSession.fromJSON(object.drop_session)
        : undefined,
      changedWatching: isSet(object.changedWatching)
        ? ChangedWatching.fromJSON(object.changedWatching)
        : isSet(object.changed_watching)
        ? ChangedWatching.fromJSON(object.changed_watching)
        : undefined,
      changedMute: isSet(object.changedMute)
        ? ChangedMute.fromJSON(object.changedMute)
        : isSet(object.changed_mute)
        ? ChangedMute.fromJSON(object.changed_mute)
        : undefined,
      changedQuality: isSet(object.changedQuality)
        ? ChangedQuality.fromJSON(object.changedQuality)
        : isSet(object.changed_quality)
        ? ChangedQuality.fromJSON(object.changed_quality)
        : undefined,
    };
  },

  toJSON(message: ServerToClient): unknown {
    const obj: any = {};
    if (message.requestRtcAnswer !== undefined) {
      obj.requestRtcAnswer = RequestRtcAnswer.toJSON(message.requestRtcAnswer);
    }
    if (message.updateVideoTransform !== undefined) {
      obj.updateVideoTransform = UpdateVideoTransform.toJSON(message.updateVideoTransform);
    }
    if (message.batteryLevel !== undefined) {
      obj.batteryLevel = BatteryLevel.toJSON(message.batteryLevel);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.updateZoom !== undefined) {
      obj.updateZoom = UpdateZoom.toJSON(message.updateZoom);
    }
    if (message.listStreamersResponse !== undefined) {
      obj.listStreamersResponse = ListStreamersResponse.toJSON(message.listStreamersResponse);
    }
    if (message.listViewersResponse !== undefined) {
      obj.listViewersResponse = ListViewersResponse.toJSON(message.listViewersResponse);
    }
    if (message.newSession !== undefined) {
      obj.newSession = NewSession.toJSON(message.newSession);
    }
    if (message.dropSession !== undefined) {
      obj.dropSession = DropSession.toJSON(message.dropSession);
    }
    if (message.changedWatching !== undefined) {
      obj.changedWatching = ChangedWatching.toJSON(message.changedWatching);
    }
    if (message.changedMute !== undefined) {
      obj.changedMute = ChangedMute.toJSON(message.changedMute);
    }
    if (message.changedQuality !== undefined) {
      obj.changedQuality = ChangedQuality.toJSON(message.changedQuality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerToClient>, I>>(base?: I): ServerToClient {
    return ServerToClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerToClient>, I>>(object: I): ServerToClient {
    const message = createBaseServerToClient();
    message.requestRtcAnswer = (object.requestRtcAnswer !== undefined && object.requestRtcAnswer !== null)
      ? RequestRtcAnswer.fromPartial(object.requestRtcAnswer)
      : undefined;
    message.updateVideoTransform = (object.updateVideoTransform !== undefined && object.updateVideoTransform !== null)
      ? UpdateVideoTransform.fromPartial(object.updateVideoTransform)
      : undefined;
    message.batteryLevel = (object.batteryLevel !== undefined && object.batteryLevel !== null)
      ? BatteryLevel.fromPartial(object.batteryLevel)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.updateZoom = (object.updateZoom !== undefined && object.updateZoom !== null)
      ? UpdateZoom.fromPartial(object.updateZoom)
      : undefined;
    message.listStreamersResponse =
      (object.listStreamersResponse !== undefined && object.listStreamersResponse !== null)
        ? ListStreamersResponse.fromPartial(object.listStreamersResponse)
        : undefined;
    message.listViewersResponse = (object.listViewersResponse !== undefined && object.listViewersResponse !== null)
      ? ListViewersResponse.fromPartial(object.listViewersResponse)
      : undefined;
    message.newSession = (object.newSession !== undefined && object.newSession !== null)
      ? NewSession.fromPartial(object.newSession)
      : undefined;
    message.dropSession = (object.dropSession !== undefined && object.dropSession !== null)
      ? DropSession.fromPartial(object.dropSession)
      : undefined;
    message.changedWatching = (object.changedWatching !== undefined && object.changedWatching !== null)
      ? ChangedWatching.fromPartial(object.changedWatching)
      : undefined;
    message.changedMute = (object.changedMute !== undefined && object.changedMute !== null)
      ? ChangedMute.fromPartial(object.changedMute)
      : undefined;
    message.changedQuality = (object.changedQuality !== undefined && object.changedQuality !== null)
      ? ChangedQuality.fromPartial(object.changedQuality)
      : undefined;
    return message;
  },
};

function createBaseRequestChangeQuality(): RequestChangeQuality {
  return { streamerId: 0, quality: 0 };
}

export const RequestChangeQuality: MessageFns<RequestChangeQuality> = {
  encode(message: RequestChangeQuality, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.quality !== 0) {
      writer.uint32(16).int32(message.quality);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestChangeQuality {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestChangeQuality();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.quality = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestChangeQuality {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      quality: isSet(object.quality) ? qualityFromJSON(object.quality) : 0,
    };
  },

  toJSON(message: RequestChangeQuality): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.quality !== 0) {
      obj.quality = qualityToJSON(message.quality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestChangeQuality>, I>>(base?: I): RequestChangeQuality {
    return RequestChangeQuality.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestChangeQuality>, I>>(object: I): RequestChangeQuality {
    const message = createBaseRequestChangeQuality();
    message.streamerId = object.streamerId ?? 0;
    message.quality = object.quality ?? 0;
    return message;
  },
};

function createBaseListStreamers(): ListStreamers {
  return {};
}

export const ListStreamers: MessageFns<ListStreamers> = {
  encode(_: ListStreamers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListStreamers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStreamers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListStreamers {
    return {};
  },

  toJSON(_: ListStreamers): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListStreamers>, I>>(base?: I): ListStreamers {
    return ListStreamers.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListStreamers>, I>>(_: I): ListStreamers {
    const message = createBaseListStreamers();
    return message;
  },
};

function createBaseListViewers(): ListViewers {
  return { streamerId: undefined };
}

export const ListViewers: MessageFns<ListViewers> = {
  encode(message: ListViewers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== undefined) {
      writer.uint32(8).uint64(message.streamerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListViewers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListViewers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListViewers {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : undefined,
    };
  },

  toJSON(message: ListViewers): unknown {
    const obj: any = {};
    if (message.streamerId !== undefined) {
      obj.streamerId = Math.round(message.streamerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListViewers>, I>>(base?: I): ListViewers {
    return ListViewers.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListViewers>, I>>(object: I): ListViewers {
    const message = createBaseListViewers();
    message.streamerId = object.streamerId ?? undefined;
    return message;
  },
};

function createBaseListAllViewers(): ListAllViewers {
  return {};
}

export const ListAllViewers: MessageFns<ListAllViewers> = {
  encode(_: ListAllViewers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAllViewers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAllViewers();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListAllViewers {
    return {};
  },

  toJSON(_: ListAllViewers): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAllViewers>, I>>(base?: I): ListAllViewers {
    return ListAllViewers.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAllViewers>, I>>(_: I): ListAllViewers {
    const message = createBaseListAllViewers();
    return message;
  },
};

function createBaseListStreamersResponse(): ListStreamersResponse {
  return { streamers: [] };
}

export const ListStreamersResponse: MessageFns<ListStreamersResponse> = {
  encode(message: ListStreamersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.streamers) {
      StreamerSession.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListStreamersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStreamersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.streamers.push(StreamerSession.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListStreamersResponse {
    return {
      streamers: globalThis.Array.isArray(object?.streamers)
        ? object.streamers.map((e: any) => StreamerSession.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListStreamersResponse): unknown {
    const obj: any = {};
    if (message.streamers?.length) {
      obj.streamers = message.streamers.map((e) => StreamerSession.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListStreamersResponse>, I>>(base?: I): ListStreamersResponse {
    return ListStreamersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListStreamersResponse>, I>>(object: I): ListStreamersResponse {
    const message = createBaseListStreamersResponse();
    message.streamers = object.streamers?.map((e) => StreamerSession.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListViewersResponse(): ListViewersResponse {
  return { viewers: [] };
}

export const ListViewersResponse: MessageFns<ListViewersResponse> = {
  encode(message: ListViewersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.viewers) {
      ViewerSession.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListViewersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListViewersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.viewers.push(ViewerSession.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListViewersResponse {
    return {
      viewers: globalThis.Array.isArray(object?.viewers)
        ? object.viewers.map((e: any) => ViewerSession.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListViewersResponse): unknown {
    const obj: any = {};
    if (message.viewers?.length) {
      obj.viewers = message.viewers.map((e) => ViewerSession.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListViewersResponse>, I>>(base?: I): ListViewersResponse {
    return ListViewersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListViewersResponse>, I>>(object: I): ListViewersResponse {
    const message = createBaseListViewersResponse();
    message.viewers = object.viewers?.map((e) => ViewerSession.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNewSession(): NewSession {
  return { streamerSession: undefined, viewerSession: undefined };
}

export const NewSession: MessageFns<NewSession> = {
  encode(message: NewSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerSession !== undefined) {
      StreamerSession.encode(message.streamerSession, writer.uint32(10).fork()).join();
    }
    if (message.viewerSession !== undefined) {
      ViewerSession.encode(message.viewerSession, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NewSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNewSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.streamerSession = StreamerSession.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.viewerSession = ViewerSession.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NewSession {
    return {
      streamerSession: isSet(object.streamerSession)
        ? StreamerSession.fromJSON(object.streamerSession)
        : isSet(object.streamer_session)
        ? StreamerSession.fromJSON(object.streamer_session)
        : undefined,
      viewerSession: isSet(object.viewerSession)
        ? ViewerSession.fromJSON(object.viewerSession)
        : isSet(object.viewer_session)
        ? ViewerSession.fromJSON(object.viewer_session)
        : undefined,
    };
  },

  toJSON(message: NewSession): unknown {
    const obj: any = {};
    if (message.streamerSession !== undefined) {
      obj.streamerSession = StreamerSession.toJSON(message.streamerSession);
    }
    if (message.viewerSession !== undefined) {
      obj.viewerSession = ViewerSession.toJSON(message.viewerSession);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NewSession>, I>>(base?: I): NewSession {
    return NewSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NewSession>, I>>(object: I): NewSession {
    const message = createBaseNewSession();
    message.streamerSession = (object.streamerSession !== undefined && object.streamerSession !== null)
      ? StreamerSession.fromPartial(object.streamerSession)
      : undefined;
    message.viewerSession = (object.viewerSession !== undefined && object.viewerSession !== null)
      ? ViewerSession.fromPartial(object.viewerSession)
      : undefined;
    return message;
  },
};

function createBaseDropSession(): DropSession {
  return { session: undefined };
}

export const DropSession: MessageFns<DropSession> = {
  encode(message: DropSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DropSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDropSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DropSession {
    return { session: isSet(object.session) ? Session.fromJSON(object.session) : undefined };
  },

  toJSON(message: DropSession): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DropSession>, I>>(base?: I): DropSession {
    return DropSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DropSession>, I>>(object: I): DropSession {
    const message = createBaseDropSession();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseChangedWatching(): ChangedWatching {
  return { viewerId: 0, streamerId: undefined };
}

export const ChangedWatching: MessageFns<ChangedWatching> = {
  encode(message: ChangedWatching, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.viewerId !== 0) {
      writer.uint32(8).uint64(message.viewerId);
    }
    if (message.streamerId !== undefined) {
      writer.uint32(16).uint64(message.streamerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangedWatching {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangedWatching();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.viewerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangedWatching {
    return {
      viewerId: isSet(object.viewerId)
        ? globalThis.Number(object.viewerId)
        : isSet(object.viewer_id)
        ? globalThis.Number(object.viewer_id)
        : 0,
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : undefined,
    };
  },

  toJSON(message: ChangedWatching): unknown {
    const obj: any = {};
    if (message.viewerId !== 0) {
      obj.viewerId = Math.round(message.viewerId);
    }
    if (message.streamerId !== undefined) {
      obj.streamerId = Math.round(message.streamerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangedWatching>, I>>(base?: I): ChangedWatching {
    return ChangedWatching.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangedWatching>, I>>(object: I): ChangedWatching {
    const message = createBaseChangedWatching();
    message.viewerId = object.viewerId ?? 0;
    message.streamerId = object.streamerId ?? undefined;
    return message;
  },
};

function createBaseStreamerSession(): StreamerSession {
  return { id: 0, name: undefined, zoom: undefined, batteryLevel: undefined };
}

export const StreamerSession: MessageFns<StreamerSession> = {
  encode(message: StreamerSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.zoom !== undefined) {
      writer.uint32(29).float(message.zoom);
    }
    if (message.batteryLevel !== undefined) {
      writer.uint32(32).uint32(message.batteryLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamerSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamerSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.zoom = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.batteryLevel = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamerSession {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : undefined,
      batteryLevel: isSet(object.batteryLevel)
        ? globalThis.Number(object.batteryLevel)
        : isSet(object.battery_level)
        ? globalThis.Number(object.battery_level)
        : undefined,
    };
  },

  toJSON(message: StreamerSession): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.zoom !== undefined) {
      obj.zoom = message.zoom;
    }
    if (message.batteryLevel !== undefined) {
      obj.batteryLevel = Math.round(message.batteryLevel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamerSession>, I>>(base?: I): StreamerSession {
    return StreamerSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamerSession>, I>>(object: I): StreamerSession {
    const message = createBaseStreamerSession();
    message.id = object.id ?? 0;
    message.name = object.name ?? undefined;
    message.zoom = object.zoom ?? undefined;
    message.batteryLevel = object.batteryLevel ?? undefined;
    return message;
  },
};

function createBaseViewerSession(): ViewerSession {
  return { id: 0, name: undefined, streamerId: undefined };
}

export const ViewerSession: MessageFns<ViewerSession> = {
  encode(message: ViewerSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.streamerId !== undefined) {
      writer.uint32(24).uint64(message.streamerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ViewerSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseViewerSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ViewerSession {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : undefined,
    };
  },

  toJSON(message: ViewerSession): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.streamerId !== undefined) {
      obj.streamerId = Math.round(message.streamerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ViewerSession>, I>>(base?: I): ViewerSession {
    return ViewerSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ViewerSession>, I>>(object: I): ViewerSession {
    const message = createBaseViewerSession();
    message.id = object.id ?? 0;
    message.name = object.name ?? undefined;
    message.streamerId = object.streamerId ?? undefined;
    return message;
  },
};

function createBaseBatteryLevel(): BatteryLevel {
  return { streamerId: 0, batteryLevel: 0 };
}

export const BatteryLevel: MessageFns<BatteryLevel> = {
  encode(message: BatteryLevel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.batteryLevel !== 0) {
      writer.uint32(16).uint32(message.batteryLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BatteryLevel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatteryLevel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.batteryLevel = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BatteryLevel {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      batteryLevel: isSet(object.batteryLevel)
        ? globalThis.Number(object.batteryLevel)
        : isSet(object.battery_level)
        ? globalThis.Number(object.battery_level)
        : 0,
    };
  },

  toJSON(message: BatteryLevel): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.batteryLevel !== 0) {
      obj.batteryLevel = Math.round(message.batteryLevel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BatteryLevel>, I>>(base?: I): BatteryLevel {
    return BatteryLevel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BatteryLevel>, I>>(object: I): BatteryLevel {
    const message = createBaseBatteryLevel();
    message.streamerId = object.streamerId ?? 0;
    message.batteryLevel = object.batteryLevel ?? 0;
    return message;
  },
};

function createBaseRequestZoom(): RequestZoom {
  return { streamerId: 0, zoom: 0 };
}

export const RequestZoom: MessageFns<RequestZoom> = {
  encode(message: RequestZoom, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.zoom !== 0) {
      writer.uint32(21).float(message.zoom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestZoom {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestZoom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.zoom = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestZoom {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0,
    };
  },

  toJSON(message: RequestZoom): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.zoom !== 0) {
      obj.zoom = message.zoom;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestZoom>, I>>(base?: I): RequestZoom {
    return RequestZoom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestZoom>, I>>(object: I): RequestZoom {
    const message = createBaseRequestZoom();
    message.streamerId = object.streamerId ?? 0;
    message.zoom = object.zoom ?? 0;
    return message;
  },
};

function createBaseUpdateZoom(): UpdateZoom {
  return { streamerId: 0, zoom: 0 };
}

export const UpdateZoom: MessageFns<UpdateZoom> = {
  encode(message: UpdateZoom, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.zoom !== 0) {
      writer.uint32(21).float(message.zoom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateZoom {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateZoom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.zoom = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateZoom {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0,
    };
  },

  toJSON(message: UpdateZoom): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.zoom !== 0) {
      obj.zoom = message.zoom;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateZoom>, I>>(base?: I): UpdateZoom {
    return UpdateZoom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateZoom>, I>>(object: I): UpdateZoom {
    const message = createBaseUpdateZoom();
    message.streamerId = object.streamerId ?? 0;
    message.zoom = object.zoom ?? 0;
    return message;
  },
};

function createBaseUpdateWatching(): UpdateWatching {
  return { viewerId: 0, streamerId: undefined };
}

export const UpdateWatching: MessageFns<UpdateWatching> = {
  encode(message: UpdateWatching, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.viewerId !== 0) {
      writer.uint32(8).uint64(message.viewerId);
    }
    if (message.streamerId !== undefined) {
      writer.uint32(16).uint64(message.streamerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWatching {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWatching();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.viewerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWatching {
    return {
      viewerId: isSet(object.viewerId)
        ? globalThis.Number(object.viewerId)
        : isSet(object.viewer_id)
        ? globalThis.Number(object.viewer_id)
        : 0,
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : undefined,
    };
  },

  toJSON(message: UpdateWatching): unknown {
    const obj: any = {};
    if (message.viewerId !== 0) {
      obj.viewerId = Math.round(message.viewerId);
    }
    if (message.streamerId !== undefined) {
      obj.streamerId = Math.round(message.streamerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWatching>, I>>(base?: I): UpdateWatching {
    return UpdateWatching.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWatching>, I>>(object: I): UpdateWatching {
    const message = createBaseUpdateWatching();
    message.viewerId = object.viewerId ?? 0;
    message.streamerId = object.streamerId ?? undefined;
    return message;
  },
};

function createBaseRequestChangeMute(): RequestChangeMute {
  return { viewerId: 0, muted: false };
}

export const RequestChangeMute: MessageFns<RequestChangeMute> = {
  encode(message: RequestChangeMute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.viewerId !== 0) {
      writer.uint32(8).uint64(message.viewerId);
    }
    if (message.muted !== false) {
      writer.uint32(16).bool(message.muted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestChangeMute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestChangeMute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.viewerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.muted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestChangeMute {
    return {
      viewerId: isSet(object.viewerId)
        ? globalThis.Number(object.viewerId)
        : isSet(object.viewer_id)
        ? globalThis.Number(object.viewer_id)
        : 0,
      muted: isSet(object.muted) ? globalThis.Boolean(object.muted) : false,
    };
  },

  toJSON(message: RequestChangeMute): unknown {
    const obj: any = {};
    if (message.viewerId !== 0) {
      obj.viewerId = Math.round(message.viewerId);
    }
    if (message.muted !== false) {
      obj.muted = message.muted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestChangeMute>, I>>(base?: I): RequestChangeMute {
    return RequestChangeMute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestChangeMute>, I>>(object: I): RequestChangeMute {
    const message = createBaseRequestChangeMute();
    message.viewerId = object.viewerId ?? 0;
    message.muted = object.muted ?? false;
    return message;
  },
};

function createBaseChangedQuality(): ChangedQuality {
  return { streamerId: 0, quality: 0 };
}

export const ChangedQuality: MessageFns<ChangedQuality> = {
  encode(message: ChangedQuality, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    if (message.quality !== 0) {
      writer.uint32(16).int32(message.quality);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangedQuality {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangedQuality();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.quality = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangedQuality {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
      quality: isSet(object.quality) ? qualityFromJSON(object.quality) : 0,
    };
  },

  toJSON(message: ChangedQuality): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    if (message.quality !== 0) {
      obj.quality = qualityToJSON(message.quality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangedQuality>, I>>(base?: I): ChangedQuality {
    return ChangedQuality.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangedQuality>, I>>(object: I): ChangedQuality {
    const message = createBaseChangedQuality();
    message.streamerId = object.streamerId ?? 0;
    message.quality = object.quality ?? 0;
    return message;
  },
};

function createBaseChangedMute(): ChangedMute {
  return { viewerId: 0, muted: false };
}

export const ChangedMute: MessageFns<ChangedMute> = {
  encode(message: ChangedMute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.viewerId !== 0) {
      writer.uint32(8).uint64(message.viewerId);
    }
    if (message.muted !== false) {
      writer.uint32(16).bool(message.muted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangedMute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangedMute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.viewerId = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.muted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangedMute {
    return {
      viewerId: isSet(object.viewerId)
        ? globalThis.Number(object.viewerId)
        : isSet(object.viewer_id)
        ? globalThis.Number(object.viewer_id)
        : 0,
      muted: isSet(object.muted) ? globalThis.Boolean(object.muted) : false,
    };
  },

  toJSON(message: ChangedMute): unknown {
    const obj: any = {};
    if (message.viewerId !== 0) {
      obj.viewerId = Math.round(message.viewerId);
    }
    if (message.muted !== false) {
      obj.muted = message.muted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangedMute>, I>>(base?: I): ChangedMute {
    return ChangedMute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangedMute>, I>>(object: I): ChangedMute {
    const message = createBaseChangedMute();
    message.viewerId = object.viewerId ?? 0;
    message.muted = object.muted ?? false;
    return message;
  },
};

function createBaseRequestRtcOffer(): RequestRtcOffer {
  return { streamerId: 0 };
}

export const RequestRtcOffer: MessageFns<RequestRtcOffer> = {
  encode(message: RequestRtcOffer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streamerId !== 0) {
      writer.uint32(8).uint64(message.streamerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestRtcOffer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestRtcOffer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streamerId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestRtcOffer {
    return {
      streamerId: isSet(object.streamerId)
        ? globalThis.Number(object.streamerId)
        : isSet(object.streamer_id)
        ? globalThis.Number(object.streamer_id)
        : 0,
    };
  },

  toJSON(message: RequestRtcOffer): unknown {
    const obj: any = {};
    if (message.streamerId !== 0) {
      obj.streamerId = Math.round(message.streamerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestRtcOffer>, I>>(base?: I): RequestRtcOffer {
    return RequestRtcOffer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestRtcOffer>, I>>(object: I): RequestRtcOffer {
    const message = createBaseRequestRtcOffer();
    message.streamerId = object.streamerId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
