// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: streamer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { IceCandidate, Quality, qualityFromJSON, qualityToJSON, Session, VideoTransform } from "./common";

export const protobufPackage = "streamer";

/** Contains the different commands that the viewer or controller can send to the streamer. */
export interface ClientToServer {
  /** Responds to the streamer WebRTC offer. */
  rtcOfferResponse?:
    | RtcOfferResponse
    | undefined;
  /** Requests the viewer or controller to update the video transform applied to the stream. */
  requestVideoTransform?:
    | RequestVideoTransform
    | undefined;
  /** Streamer is updating their battery level. */
  updateBatteryLevel?:
    | UpdateBatteryLevel
    | undefined;
  /** Sent the ICE candidate to the viewer or controller. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** The streamer has updated the zoom level applied to the stream. */
  requestZoom?:
    | Zoom
    | undefined;
  /** The streamer has updated the quality of the stream. */
  changeQualityResponse?: ChangeQualityResponse | undefined;
}

/** Contains the different commands that the server can send to the streamer. */
export interface ServerToClient {
  /** The viewer or controller is requesting an WebRTC offer from the streamer to establish a WebRTC connection. */
  requestRtcOffer?:
    | RequestRtcOffer
    | undefined;
  /** The viewer or controller is responding to the streamer's WebRTC offer with an answer to establish a WebRTC connection. */
  rtcAnswer?:
    | RtcAnswer
    | undefined;
  /** The streamer will send an ICE candidate to the viewer or controller to establish a WebRTC connection. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** The viewer or controller is requesting to disconnect from the streamer. */
  disconnectPeer?:
    | DisconnectPeer
    | undefined;
  /** The controller is requesting the streamer to update the zoom level applied to the stream. */
  changeZoom?:
    | Zoom
    | undefined;
  /** The controller is requesting the streamer to change the quality of the stream. */
  changeQuality?: ChangeQuality | undefined;
}

/** Requests the streamer to create an RTC offer for the viewer or controller to establish a WebRTC connection. */
export interface RequestRtcOffer {
  /** Who is requesting the RTC offer. */
  session: Session | undefined;
}

/** / Response to the viewer or controller's request for an RTC offer, containing the SDP of the RTC offer. */
export interface RtcOfferResponse {
  /** The session that requested the RTC offer. */
  session:
    | Session
    | undefined;
  /** The offer created by the streamer in response to the viewer or controller's request. */
  offer: string;
}

/** / Answer from the viewer or controller to the streamer in response to the RTC offer created by the streamer. */
export interface RtcAnswer {
  /** The session that responded to the RTC offer. */
  session:
    | Session
    | undefined;
  /** The answer created by the viewer or controller in response to the RTC offer created by the streamer. */
  answer: string;
}

/** Requests the streamer to disconnect the WebRTC connection with the viewer or controller. */
export interface DisconnectPeer {
  /** The session that needs to have disconnected from the streamer. */
  session: Session | undefined;
}

/** Requests all viewers and controllers to update the video transform applied to the stream. */
export interface RequestVideoTransform {
  /** The new video transform the streamer is requesting to apply to the stream. */
  videoTransform: VideoTransform | undefined;
}

/** Sent by the streamer to the controller when the streamer updates its battery level. */
export interface UpdateBatteryLevel {
  /** The new battery level of the streamer's device as a percentage from 0 to 100. */
  batteryLevel: number;
}

/** Sent to the streamer to update the quality of the stream. */
export interface ChangeQuality {
  /** The new quality the streamer is requesting to apply to the stream. */
  quality: Quality;
}

/** A request and event for updating the zoom level applied to the stream. */
export interface Zoom {
  /** The new zoom level the streamer is requesting or reporting. A value of 1.0 means no zoom, while a value greater than 1.0 means zoom in and a value less than 1.0 means zoom out. */
  zoom: number;
}

/** A response from the streamer to the controller confirming the new quality of the stream. */
export interface ChangeQualityResponse {
  /** The new quality the streamer is applying to the stream. */
  quality: Quality;
}

function createBaseClientToServer(): ClientToServer {
  return {
    rtcOfferResponse: undefined,
    requestVideoTransform: undefined,
    updateBatteryLevel: undefined,
    iceCandidate: undefined,
    requestZoom: undefined,
    changeQualityResponse: undefined,
  };
}

export const ClientToServer: MessageFns<ClientToServer> = {
  encode(message: ClientToServer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rtcOfferResponse !== undefined) {
      RtcOfferResponse.encode(message.rtcOfferResponse, writer.uint32(10).fork()).join();
    }
    if (message.requestVideoTransform !== undefined) {
      RequestVideoTransform.encode(message.requestVideoTransform, writer.uint32(18).fork()).join();
    }
    if (message.updateBatteryLevel !== undefined) {
      UpdateBatteryLevel.encode(message.updateBatteryLevel, writer.uint32(26).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(34).fork()).join();
    }
    if (message.requestZoom !== undefined) {
      Zoom.encode(message.requestZoom, writer.uint32(42).fork()).join();
    }
    if (message.changeQualityResponse !== undefined) {
      ChangeQualityResponse.encode(message.changeQualityResponse, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientToServer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientToServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rtcOfferResponse = RtcOfferResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requestVideoTransform = RequestVideoTransform.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updateBatteryLevel = UpdateBatteryLevel.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.requestZoom = Zoom.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.changeQualityResponse = ChangeQualityResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientToServer {
    return {
      rtcOfferResponse: isSet(object.rtcOfferResponse)
        ? RtcOfferResponse.fromJSON(object.rtcOfferResponse)
        : isSet(object.rtc_offer_response)
        ? RtcOfferResponse.fromJSON(object.rtc_offer_response)
        : undefined,
      requestVideoTransform: isSet(object.requestVideoTransform)
        ? RequestVideoTransform.fromJSON(object.requestVideoTransform)
        : isSet(object.request_video_transform)
        ? RequestVideoTransform.fromJSON(object.request_video_transform)
        : undefined,
      updateBatteryLevel: isSet(object.updateBatteryLevel)
        ? UpdateBatteryLevel.fromJSON(object.updateBatteryLevel)
        : isSet(object.update_battery_level)
        ? UpdateBatteryLevel.fromJSON(object.update_battery_level)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      requestZoom: isSet(object.requestZoom)
        ? Zoom.fromJSON(object.requestZoom)
        : isSet(object.request_zoom)
        ? Zoom.fromJSON(object.request_zoom)
        : undefined,
      changeQualityResponse: isSet(object.changeQualityResponse)
        ? ChangeQualityResponse.fromJSON(object.changeQualityResponse)
        : isSet(object.change_quality_response)
        ? ChangeQualityResponse.fromJSON(object.change_quality_response)
        : undefined,
    };
  },

  toJSON(message: ClientToServer): unknown {
    const obj: any = {};
    if (message.rtcOfferResponse !== undefined) {
      obj.rtcOfferResponse = RtcOfferResponse.toJSON(message.rtcOfferResponse);
    }
    if (message.requestVideoTransform !== undefined) {
      obj.requestVideoTransform = RequestVideoTransform.toJSON(message.requestVideoTransform);
    }
    if (message.updateBatteryLevel !== undefined) {
      obj.updateBatteryLevel = UpdateBatteryLevel.toJSON(message.updateBatteryLevel);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.requestZoom !== undefined) {
      obj.requestZoom = Zoom.toJSON(message.requestZoom);
    }
    if (message.changeQualityResponse !== undefined) {
      obj.changeQualityResponse = ChangeQualityResponse.toJSON(message.changeQualityResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientToServer>, I>>(base?: I): ClientToServer {
    return ClientToServer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientToServer>, I>>(object: I): ClientToServer {
    const message = createBaseClientToServer();
    message.rtcOfferResponse = (object.rtcOfferResponse !== undefined && object.rtcOfferResponse !== null)
      ? RtcOfferResponse.fromPartial(object.rtcOfferResponse)
      : undefined;
    message.requestVideoTransform =
      (object.requestVideoTransform !== undefined && object.requestVideoTransform !== null)
        ? RequestVideoTransform.fromPartial(object.requestVideoTransform)
        : undefined;
    message.updateBatteryLevel = (object.updateBatteryLevel !== undefined && object.updateBatteryLevel !== null)
      ? UpdateBatteryLevel.fromPartial(object.updateBatteryLevel)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.requestZoom = (object.requestZoom !== undefined && object.requestZoom !== null)
      ? Zoom.fromPartial(object.requestZoom)
      : undefined;
    message.changeQualityResponse =
      (object.changeQualityResponse !== undefined && object.changeQualityResponse !== null)
        ? ChangeQualityResponse.fromPartial(object.changeQualityResponse)
        : undefined;
    return message;
  },
};

function createBaseServerToClient(): ServerToClient {
  return {
    requestRtcOffer: undefined,
    rtcAnswer: undefined,
    iceCandidate: undefined,
    disconnectPeer: undefined,
    changeZoom: undefined,
    changeQuality: undefined,
  };
}

export const ServerToClient: MessageFns<ServerToClient> = {
  encode(message: ServerToClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestRtcOffer !== undefined) {
      RequestRtcOffer.encode(message.requestRtcOffer, writer.uint32(10).fork()).join();
    }
    if (message.rtcAnswer !== undefined) {
      RtcAnswer.encode(message.rtcAnswer, writer.uint32(18).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(26).fork()).join();
    }
    if (message.disconnectPeer !== undefined) {
      DisconnectPeer.encode(message.disconnectPeer, writer.uint32(34).fork()).join();
    }
    if (message.changeZoom !== undefined) {
      Zoom.encode(message.changeZoom, writer.uint32(42).fork()).join();
    }
    if (message.changeQuality !== undefined) {
      ChangeQuality.encode(message.changeQuality, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerToClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerToClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestRtcOffer = RequestRtcOffer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rtcAnswer = RtcAnswer.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.disconnectPeer = DisconnectPeer.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.changeZoom = Zoom.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.changeQuality = ChangeQuality.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerToClient {
    return {
      requestRtcOffer: isSet(object.requestRtcOffer)
        ? RequestRtcOffer.fromJSON(object.requestRtcOffer)
        : isSet(object.request_rtc_offer)
        ? RequestRtcOffer.fromJSON(object.request_rtc_offer)
        : undefined,
      rtcAnswer: isSet(object.rtcAnswer)
        ? RtcAnswer.fromJSON(object.rtcAnswer)
        : isSet(object.rtc_answer)
        ? RtcAnswer.fromJSON(object.rtc_answer)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      disconnectPeer: isSet(object.disconnectPeer)
        ? DisconnectPeer.fromJSON(object.disconnectPeer)
        : isSet(object.disconnect_peer)
        ? DisconnectPeer.fromJSON(object.disconnect_peer)
        : undefined,
      changeZoom: isSet(object.changeZoom)
        ? Zoom.fromJSON(object.changeZoom)
        : isSet(object.change_zoom)
        ? Zoom.fromJSON(object.change_zoom)
        : undefined,
      changeQuality: isSet(object.changeQuality)
        ? ChangeQuality.fromJSON(object.changeQuality)
        : isSet(object.change_quality)
        ? ChangeQuality.fromJSON(object.change_quality)
        : undefined,
    };
  },

  toJSON(message: ServerToClient): unknown {
    const obj: any = {};
    if (message.requestRtcOffer !== undefined) {
      obj.requestRtcOffer = RequestRtcOffer.toJSON(message.requestRtcOffer);
    }
    if (message.rtcAnswer !== undefined) {
      obj.rtcAnswer = RtcAnswer.toJSON(message.rtcAnswer);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.disconnectPeer !== undefined) {
      obj.disconnectPeer = DisconnectPeer.toJSON(message.disconnectPeer);
    }
    if (message.changeZoom !== undefined) {
      obj.changeZoom = Zoom.toJSON(message.changeZoom);
    }
    if (message.changeQuality !== undefined) {
      obj.changeQuality = ChangeQuality.toJSON(message.changeQuality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerToClient>, I>>(base?: I): ServerToClient {
    return ServerToClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerToClient>, I>>(object: I): ServerToClient {
    const message = createBaseServerToClient();
    message.requestRtcOffer = (object.requestRtcOffer !== undefined && object.requestRtcOffer !== null)
      ? RequestRtcOffer.fromPartial(object.requestRtcOffer)
      : undefined;
    message.rtcAnswer = (object.rtcAnswer !== undefined && object.rtcAnswer !== null)
      ? RtcAnswer.fromPartial(object.rtcAnswer)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.disconnectPeer = (object.disconnectPeer !== undefined && object.disconnectPeer !== null)
      ? DisconnectPeer.fromPartial(object.disconnectPeer)
      : undefined;
    message.changeZoom = (object.changeZoom !== undefined && object.changeZoom !== null)
      ? Zoom.fromPartial(object.changeZoom)
      : undefined;
    message.changeQuality = (object.changeQuality !== undefined && object.changeQuality !== null)
      ? ChangeQuality.fromPartial(object.changeQuality)
      : undefined;
    return message;
  },
};

function createBaseRequestRtcOffer(): RequestRtcOffer {
  return { session: undefined };
}

export const RequestRtcOffer: MessageFns<RequestRtcOffer> = {
  encode(message: RequestRtcOffer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestRtcOffer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestRtcOffer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestRtcOffer {
    return { session: isSet(object.session) ? Session.fromJSON(object.session) : undefined };
  },

  toJSON(message: RequestRtcOffer): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestRtcOffer>, I>>(base?: I): RequestRtcOffer {
    return RequestRtcOffer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestRtcOffer>, I>>(object: I): RequestRtcOffer {
    const message = createBaseRequestRtcOffer();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseRtcOfferResponse(): RtcOfferResponse {
  return { session: undefined, offer: "" };
}

export const RtcOfferResponse: MessageFns<RtcOfferResponse> = {
  encode(message: RtcOfferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.offer !== "") {
      writer.uint32(18).string(message.offer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcOfferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcOfferResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.offer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RtcOfferResponse {
    return {
      session: isSet(object.session) ? Session.fromJSON(object.session) : undefined,
      offer: isSet(object.offer) ? globalThis.String(object.offer) : "",
    };
  },

  toJSON(message: RtcOfferResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.offer !== "") {
      obj.offer = message.offer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RtcOfferResponse>, I>>(base?: I): RtcOfferResponse {
    return RtcOfferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcOfferResponse>, I>>(object: I): RtcOfferResponse {
    const message = createBaseRtcOfferResponse();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    message.offer = object.offer ?? "";
    return message;
  },
};

function createBaseRtcAnswer(): RtcAnswer {
  return { session: undefined, answer: "" };
}

export const RtcAnswer: MessageFns<RtcAnswer> = {
  encode(message: RtcAnswer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.answer !== "") {
      writer.uint32(18).string(message.answer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcAnswer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcAnswer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RtcAnswer {
    return {
      session: isSet(object.session) ? Session.fromJSON(object.session) : undefined,
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
    };
  },

  toJSON(message: RtcAnswer): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RtcAnswer>, I>>(base?: I): RtcAnswer {
    return RtcAnswer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcAnswer>, I>>(object: I): RtcAnswer {
    const message = createBaseRtcAnswer();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    message.answer = object.answer ?? "";
    return message;
  },
};

function createBaseDisconnectPeer(): DisconnectPeer {
  return { session: undefined };
}

export const DisconnectPeer: MessageFns<DisconnectPeer> = {
  encode(message: DisconnectPeer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisconnectPeer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisconnectPeer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisconnectPeer {
    return { session: isSet(object.session) ? Session.fromJSON(object.session) : undefined };
  },

  toJSON(message: DisconnectPeer): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisconnectPeer>, I>>(base?: I): DisconnectPeer {
    return DisconnectPeer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisconnectPeer>, I>>(object: I): DisconnectPeer {
    const message = createBaseDisconnectPeer();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseRequestVideoTransform(): RequestVideoTransform {
  return { videoTransform: undefined };
}

export const RequestVideoTransform: MessageFns<RequestVideoTransform> = {
  encode(message: RequestVideoTransform, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videoTransform !== undefined) {
      VideoTransform.encode(message.videoTransform, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestVideoTransform {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestVideoTransform();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.videoTransform = VideoTransform.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestVideoTransform {
    return {
      videoTransform: isSet(object.videoTransform)
        ? VideoTransform.fromJSON(object.videoTransform)
        : isSet(object.video_transform)
        ? VideoTransform.fromJSON(object.video_transform)
        : undefined,
    };
  },

  toJSON(message: RequestVideoTransform): unknown {
    const obj: any = {};
    if (message.videoTransform !== undefined) {
      obj.videoTransform = VideoTransform.toJSON(message.videoTransform);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestVideoTransform>, I>>(base?: I): RequestVideoTransform {
    return RequestVideoTransform.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestVideoTransform>, I>>(object: I): RequestVideoTransform {
    const message = createBaseRequestVideoTransform();
    message.videoTransform = (object.videoTransform !== undefined && object.videoTransform !== null)
      ? VideoTransform.fromPartial(object.videoTransform)
      : undefined;
    return message;
  },
};

function createBaseUpdateBatteryLevel(): UpdateBatteryLevel {
  return { batteryLevel: 0 };
}

export const UpdateBatteryLevel: MessageFns<UpdateBatteryLevel> = {
  encode(message: UpdateBatteryLevel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.batteryLevel !== 0) {
      writer.uint32(8).uint32(message.batteryLevel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateBatteryLevel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateBatteryLevel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.batteryLevel = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateBatteryLevel {
    return {
      batteryLevel: isSet(object.batteryLevel)
        ? globalThis.Number(object.batteryLevel)
        : isSet(object.battery_level)
        ? globalThis.Number(object.battery_level)
        : 0,
    };
  },

  toJSON(message: UpdateBatteryLevel): unknown {
    const obj: any = {};
    if (message.batteryLevel !== 0) {
      obj.batteryLevel = Math.round(message.batteryLevel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateBatteryLevel>, I>>(base?: I): UpdateBatteryLevel {
    return UpdateBatteryLevel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateBatteryLevel>, I>>(object: I): UpdateBatteryLevel {
    const message = createBaseUpdateBatteryLevel();
    message.batteryLevel = object.batteryLevel ?? 0;
    return message;
  },
};

function createBaseChangeQuality(): ChangeQuality {
  return { quality: 0 };
}

export const ChangeQuality: MessageFns<ChangeQuality> = {
  encode(message: ChangeQuality, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quality !== 0) {
      writer.uint32(8).int32(message.quality);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeQuality {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeQuality();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.quality = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangeQuality {
    return { quality: isSet(object.quality) ? qualityFromJSON(object.quality) : 0 };
  },

  toJSON(message: ChangeQuality): unknown {
    const obj: any = {};
    if (message.quality !== 0) {
      obj.quality = qualityToJSON(message.quality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeQuality>, I>>(base?: I): ChangeQuality {
    return ChangeQuality.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeQuality>, I>>(object: I): ChangeQuality {
    const message = createBaseChangeQuality();
    message.quality = object.quality ?? 0;
    return message;
  },
};

function createBaseZoom(): Zoom {
  return { zoom: 0 };
}

export const Zoom: MessageFns<Zoom> = {
  encode(message: Zoom, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.zoom !== 0) {
      writer.uint32(13).float(message.zoom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Zoom {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZoom();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.zoom = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Zoom {
    return { zoom: isSet(object.zoom) ? globalThis.Number(object.zoom) : 0 };
  },

  toJSON(message: Zoom): unknown {
    const obj: any = {};
    if (message.zoom !== 0) {
      obj.zoom = message.zoom;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Zoom>, I>>(base?: I): Zoom {
    return Zoom.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Zoom>, I>>(object: I): Zoom {
    const message = createBaseZoom();
    message.zoom = object.zoom ?? 0;
    return message;
  },
};

function createBaseChangeQualityResponse(): ChangeQualityResponse {
  return { quality: 0 };
}

export const ChangeQualityResponse: MessageFns<ChangeQualityResponse> = {
  encode(message: ChangeQualityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.quality !== 0) {
      writer.uint32(8).int32(message.quality);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeQualityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeQualityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.quality = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangeQualityResponse {
    return { quality: isSet(object.quality) ? qualityFromJSON(object.quality) : 0 };
  },

  toJSON(message: ChangeQualityResponse): unknown {
    const obj: any = {};
    if (message.quality !== 0) {
      obj.quality = qualityToJSON(message.quality);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeQualityResponse>, I>>(base?: I): ChangeQualityResponse {
    return ChangeQualityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeQualityResponse>, I>>(object: I): ChangeQualityResponse {
    const message = createBaseChangeQualityResponse();
    message.quality = object.quality ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
