// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: viewer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { IceCandidate, RequestRtcAnswer, RtcAnswerResponse, UpdateVideoTransform } from "./common";

export const protobufPackage = "viewer";

/** Contains the different commands that the viewer can send to the server. */
export interface ClientToServer {
  /** Responds to the streamer WebRTC offer. */
  rtcAnswerResponse?:
    | RtcAnswerResponse
    | undefined;
  /** The viewer is sending an ICE candidate to the streamer to establish a WebRTC connection. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** The viewer has updated the mute status of their own stream. */
  updateMuteResponse?: UpdateMuteResponse | undefined;
}

/** Contains the different commands that the server can send to the viewer. */
export interface ServerToClient {
  /** The streamer is requesting the viewer to answer the RTC offer created by the streamer to establish a WebRTC connection. */
  requestRtcAnswer?:
    | RequestRtcAnswer
    | undefined;
  /** The streamer will send a request to update the video transform applied to the stream when the streamer requests it. */
  updateVideoTransform?:
    | UpdateVideoTransform
    | undefined;
  /** The streamer will send an ICE candidate to the viewer to establish a WebRTC connection. */
  iceCandidate?:
    | IceCandidate
    | undefined;
  /** The server will send a notification to the viewer when the streamer they are watching has disconnected from the server. */
  disconnectStreamer?:
    | DisconnectStreamer
    | undefined;
  /** The controller is requesting the viewer to update the mute status of the stream. */
  updateMute?: UpdateMute | undefined;
}

/** A command sent when streamer disconnect or controller requests a viewer to disconnect from a streamer. */
export interface DisconnectStreamer {
}

/** Requests the viewer to update its mute status of the stream. */
export interface UpdateMute {
  /** The new mute status to set for the stream. A value of true means to mute the stream, while a value of false means to un-mute the stream. */
  muted: boolean;
}

/** The viewer has updated the mute status of their own stream. */
export interface UpdateMuteResponse {
  /** The new mute status that the viewer has changed to. A value of true means the stream is now muted, while a value of false means the stream is now un-muted. */
  muted: boolean;
}

function createBaseClientToServer(): ClientToServer {
  return { rtcAnswerResponse: undefined, iceCandidate: undefined, updateMuteResponse: undefined };
}

export const ClientToServer: MessageFns<ClientToServer> = {
  encode(message: ClientToServer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rtcAnswerResponse !== undefined) {
      RtcAnswerResponse.encode(message.rtcAnswerResponse, writer.uint32(10).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(18).fork()).join();
    }
    if (message.updateMuteResponse !== undefined) {
      UpdateMuteResponse.encode(message.updateMuteResponse, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientToServer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientToServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rtcAnswerResponse = RtcAnswerResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updateMuteResponse = UpdateMuteResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientToServer {
    return {
      rtcAnswerResponse: isSet(object.rtcAnswerResponse)
        ? RtcAnswerResponse.fromJSON(object.rtcAnswerResponse)
        : isSet(object.rtc_answer_response)
        ? RtcAnswerResponse.fromJSON(object.rtc_answer_response)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      updateMuteResponse: isSet(object.updateMuteResponse)
        ? UpdateMuteResponse.fromJSON(object.updateMuteResponse)
        : isSet(object.update_mute_response)
        ? UpdateMuteResponse.fromJSON(object.update_mute_response)
        : undefined,
    };
  },

  toJSON(message: ClientToServer): unknown {
    const obj: any = {};
    if (message.rtcAnswerResponse !== undefined) {
      obj.rtcAnswerResponse = RtcAnswerResponse.toJSON(message.rtcAnswerResponse);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.updateMuteResponse !== undefined) {
      obj.updateMuteResponse = UpdateMuteResponse.toJSON(message.updateMuteResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientToServer>, I>>(base?: I): ClientToServer {
    return ClientToServer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientToServer>, I>>(object: I): ClientToServer {
    const message = createBaseClientToServer();
    message.rtcAnswerResponse = (object.rtcAnswerResponse !== undefined && object.rtcAnswerResponse !== null)
      ? RtcAnswerResponse.fromPartial(object.rtcAnswerResponse)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.updateMuteResponse = (object.updateMuteResponse !== undefined && object.updateMuteResponse !== null)
      ? UpdateMuteResponse.fromPartial(object.updateMuteResponse)
      : undefined;
    return message;
  },
};

function createBaseServerToClient(): ServerToClient {
  return {
    requestRtcAnswer: undefined,
    updateVideoTransform: undefined,
    iceCandidate: undefined,
    disconnectStreamer: undefined,
    updateMute: undefined,
  };
}

export const ServerToClient: MessageFns<ServerToClient> = {
  encode(message: ServerToClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestRtcAnswer !== undefined) {
      RequestRtcAnswer.encode(message.requestRtcAnswer, writer.uint32(10).fork()).join();
    }
    if (message.updateVideoTransform !== undefined) {
      UpdateVideoTransform.encode(message.updateVideoTransform, writer.uint32(18).fork()).join();
    }
    if (message.iceCandidate !== undefined) {
      IceCandidate.encode(message.iceCandidate, writer.uint32(26).fork()).join();
    }
    if (message.disconnectStreamer !== undefined) {
      DisconnectStreamer.encode(message.disconnectStreamer, writer.uint32(34).fork()).join();
    }
    if (message.updateMute !== undefined) {
      UpdateMute.encode(message.updateMute, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerToClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerToClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestRtcAnswer = RequestRtcAnswer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateVideoTransform = UpdateVideoTransform.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.iceCandidate = IceCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.disconnectStreamer = DisconnectStreamer.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updateMute = UpdateMute.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerToClient {
    return {
      requestRtcAnswer: isSet(object.requestRtcAnswer)
        ? RequestRtcAnswer.fromJSON(object.requestRtcAnswer)
        : isSet(object.request_rtc_answer)
        ? RequestRtcAnswer.fromJSON(object.request_rtc_answer)
        : undefined,
      updateVideoTransform: isSet(object.updateVideoTransform)
        ? UpdateVideoTransform.fromJSON(object.updateVideoTransform)
        : isSet(object.update_video_transform)
        ? UpdateVideoTransform.fromJSON(object.update_video_transform)
        : undefined,
      iceCandidate: isSet(object.iceCandidate)
        ? IceCandidate.fromJSON(object.iceCandidate)
        : isSet(object.ice_candidate)
        ? IceCandidate.fromJSON(object.ice_candidate)
        : undefined,
      disconnectStreamer: isSet(object.disconnectStreamer)
        ? DisconnectStreamer.fromJSON(object.disconnectStreamer)
        : isSet(object.disconnect_streamer)
        ? DisconnectStreamer.fromJSON(object.disconnect_streamer)
        : undefined,
      updateMute: isSet(object.updateMute)
        ? UpdateMute.fromJSON(object.updateMute)
        : isSet(object.update_mute)
        ? UpdateMute.fromJSON(object.update_mute)
        : undefined,
    };
  },

  toJSON(message: ServerToClient): unknown {
    const obj: any = {};
    if (message.requestRtcAnswer !== undefined) {
      obj.requestRtcAnswer = RequestRtcAnswer.toJSON(message.requestRtcAnswer);
    }
    if (message.updateVideoTransform !== undefined) {
      obj.updateVideoTransform = UpdateVideoTransform.toJSON(message.updateVideoTransform);
    }
    if (message.iceCandidate !== undefined) {
      obj.iceCandidate = IceCandidate.toJSON(message.iceCandidate);
    }
    if (message.disconnectStreamer !== undefined) {
      obj.disconnectStreamer = DisconnectStreamer.toJSON(message.disconnectStreamer);
    }
    if (message.updateMute !== undefined) {
      obj.updateMute = UpdateMute.toJSON(message.updateMute);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerToClient>, I>>(base?: I): ServerToClient {
    return ServerToClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerToClient>, I>>(object: I): ServerToClient {
    const message = createBaseServerToClient();
    message.requestRtcAnswer = (object.requestRtcAnswer !== undefined && object.requestRtcAnswer !== null)
      ? RequestRtcAnswer.fromPartial(object.requestRtcAnswer)
      : undefined;
    message.updateVideoTransform = (object.updateVideoTransform !== undefined && object.updateVideoTransform !== null)
      ? UpdateVideoTransform.fromPartial(object.updateVideoTransform)
      : undefined;
    message.iceCandidate = (object.iceCandidate !== undefined && object.iceCandidate !== null)
      ? IceCandidate.fromPartial(object.iceCandidate)
      : undefined;
    message.disconnectStreamer = (object.disconnectStreamer !== undefined && object.disconnectStreamer !== null)
      ? DisconnectStreamer.fromPartial(object.disconnectStreamer)
      : undefined;
    message.updateMute = (object.updateMute !== undefined && object.updateMute !== null)
      ? UpdateMute.fromPartial(object.updateMute)
      : undefined;
    return message;
  },
};

function createBaseDisconnectStreamer(): DisconnectStreamer {
  return {};
}

export const DisconnectStreamer: MessageFns<DisconnectStreamer> = {
  encode(_: DisconnectStreamer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisconnectStreamer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisconnectStreamer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DisconnectStreamer {
    return {};
  },

  toJSON(_: DisconnectStreamer): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DisconnectStreamer>, I>>(base?: I): DisconnectStreamer {
    return DisconnectStreamer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisconnectStreamer>, I>>(_: I): DisconnectStreamer {
    const message = createBaseDisconnectStreamer();
    return message;
  },
};

function createBaseUpdateMute(): UpdateMute {
  return { muted: false };
}

export const UpdateMute: MessageFns<UpdateMute> = {
  encode(message: UpdateMute, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.muted !== false) {
      writer.uint32(16).bool(message.muted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMute {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMute();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.muted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMute {
    return { muted: isSet(object.muted) ? globalThis.Boolean(object.muted) : false };
  },

  toJSON(message: UpdateMute): unknown {
    const obj: any = {};
    if (message.muted !== false) {
      obj.muted = message.muted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMute>, I>>(base?: I): UpdateMute {
    return UpdateMute.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMute>, I>>(object: I): UpdateMute {
    const message = createBaseUpdateMute();
    message.muted = object.muted ?? false;
    return message;
  },
};

function createBaseUpdateMuteResponse(): UpdateMuteResponse {
  return { muted: false };
}

export const UpdateMuteResponse: MessageFns<UpdateMuteResponse> = {
  encode(message: UpdateMuteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.muted !== false) {
      writer.uint32(8).bool(message.muted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMuteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMuteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.muted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMuteResponse {
    return { muted: isSet(object.muted) ? globalThis.Boolean(object.muted) : false };
  },

  toJSON(message: UpdateMuteResponse): unknown {
    const obj: any = {};
    if (message.muted !== false) {
      obj.muted = message.muted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMuteResponse>, I>>(base?: I): UpdateMuteResponse {
    return UpdateMuteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMuteResponse>, I>>(object: I): UpdateMuteResponse {
    const message = createBaseUpdateMuteResponse();
    message.muted = object.muted ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
